import { defineConfig } from "drizzle-kit";

// One SQLite file per state directory (docs/ARCHITECTURE.md §8). Migrations are
// generated by drizzle-kit and committed as SQL under src/db/migrations.
const stateDir = process.env.AGENT_STATE_DIR ?? "./data";

export default defineConfig({
  dialect: "sqlite",
  schema: "./src/db/schema.ts",
  out: "./src/db/migrations",
  dbCredentials: {
    url: `${stateDir}/revenue-desk.sqlite`,
  },
  strict: true,
  verbose: true,
});
